spring.application.name=se-group-project
spring.thymeleaf.cache=false
server.port=${SERVER_PORT:5001}
spring.config.import=optional:file:.env[.properties]

# SQLite Configuration
spring.datasource.url=jdbc:sqlite:se_project_db.sqlite
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
