spring.application.name=se-group-project
spring.thymeleaf.cache=false
server.port=${SERVER_PORT:5001}
spring.config.import=optional:file:.env[.properties]

# MongoDB Configuration
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017}
spring.data.mongodb.database=${MONGODB_DATABASE:se_project_db}
spring.data.mongodb.auto-index-creation=true

